# Generated by Django 5.1.1 on 2024-10-08 09:14

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    dependencies: list[tuple[str, str]] = [
        ('polls', '0001_initial'),
    ]

    operations: list[Operation] = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
